### ISSUE TITLE
It is compatible with lumen 5.6.+?

### ISSUE THREAD

**Issue by marcoadasilvaa** [digitaldreams/laracrud#20]
It is compatible with lumen 5.6.+?

After add "digitaldream/laracrud": "3.*" on composer.json

```
composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 5 installs, 2 updates, 24 removals
  - Removing illuminate/console (v5.6.20)
  - Removing illuminate/routing (v5.6.20)
  - Removing illuminate/session (v5.6.20)
  - Removing illuminate/view (v5.6.20)
  - Removing illuminate/validation (v5.6.20)
  - Removing illuminate/translation (v5.6.20)
  - Removing illuminate/support (v5.6.20)
  - Removing illuminate/queue (v5.6.20)
  - Removing illuminate/pipeline (v5.6.20)
  - Removing illuminate/pagination (v5.6.20)
  - Removing illuminate/log (v5.6.20)
  - Removing illuminate/http (v5.6.20)
  - Removing illuminate/hashing (v5.6.20)
  - Removing illuminate/filesystem (v5.6.20)
  - Removing illuminate/events (v5.6.20)
  - Removing illuminate/encryption (v5.6.20)
  - Removing illuminate/container (v5.6.20)
  - Removing illuminate/config (v5.6.20)
  - Removing illuminate/cache (v5.6.20)
  - Removing illuminate/bus (v5.6.20)
  - Removing illuminate/broadcasting (v5.6.20)
  - Removing illuminate/mail (v5.6.20)
  - Removing illuminate/database (v5.6.20)
  - Removing illuminate/auth (v5.6.20)
  - Updating nesbot/carbon (1.27.0 => 1.25.0): Loading from cache
  - Installing digitaldream/dbreader (1.4): Downloading (100%)         
  - Installing paragonie/random_compat (v2.0.12): Loading from cache
  - Installing ramsey/uuid (3.7.3): Loading from cache
  - Installing league/flysystem (1.0.44): Loading from cache
  - Updating laravel/framework (v5.6.20 => v5.6.20): Downloading (100%)         
  - Installing digitaldream/laracrud (3.1.1): Downloading (100%)         
paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
ramsey/uuid suggests installing ircmaxell/random-lib (Provides RandomLib for use with the RandomLibAdapter)
ramsey/uuid suggests installing ext-libsodium (Provides the PECL libsodium extension for use with the SodiumRandomGenerator)
ramsey/uuid suggests installing ext-uuid (Provides the PECL UUID extension for use with the PeclUuidTimeGenerator and PeclUuidRandomGenerator)
ramsey/uuid suggests installing moontoast/math (Provides support for converting UUID to 128-bit integer (in string form).)
ramsey/uuid suggests installing ramsey/uuid-doctrine (Allows the use of Ramsey\Uuid\Uuid as Doctrine field type.)
ramsey/uuid suggests installing ramsey/uuid-console (A console application for generating UUIDs with ramsey/uuid)
league/flysystem suggests installing league/flysystem-aws-s3-v2 (Allows you to use S3 storage with AWS SDK v2)
league/flysystem suggests installing league/flysystem-aws-s3-v3 (Allows you to use S3 storage with AWS SDK v3)
league/flysystem suggests installing league/flysystem-azure (Allows you to use Windows Azure Blob storage)
league/flysystem suggests installing league/flysystem-cached-adapter (Flysystem adapter decorator for metadata caching)
league/flysystem suggests installing league/flysystem-eventable-filesystem (Allows you to use EventableFilesystem)
league/flysystem suggests installing league/flysystem-rackspace (Allows you to use Rackspace Cloud Files)
league/flysystem suggests installing league/flysystem-sftp (Allows you to use SFTP server storage via phpseclib)
league/flysystem suggests installing league/flysystem-webdav (Allows you to use WebDAV storage)
league/flysystem suggests installing league/flysystem-ziparchive (Allows you to use ZipArchive adapter)
league/flysystem suggests installing spatie/flysystem-dropbox (Allows you to use Dropbox storage)
league/flysystem suggests installing srmklive/flysystem-dropbox-v2 (Allows you to use Dropbox storage for PHP 5 applications)
digitaldream/laracrud suggests installing intervention/image (For Image)
digitaldream/laracrud suggests installing tymon/jwt-auth (For API authentication)
digitaldream/laracrud suggests installing dingo/api (To make API)
Writing lock file
Generating autoload files
marcodasilva@LAPTOP-MADSA01:/data/www/eureka/APJ-api$ php artisan
PHP Fatal error:  Uncaught ReflectionException: Class path.storage does not exist in /data/www/eureka/APJ-api/vendor/laravel/framework/src/Illuminate/Container/Container.php:767
Stack trace:
#0 /data/www/eureka/APJ-api/vendor/laravel/framework/src/Illuminate/Container/Container.php(767): ReflectionClass->__construct('path.storage')
#1 /data/www/eureka/APJ-api/vendor/laravel/framework/src/Illuminate/Container/Container.php(646): Illuminate\Container\Container->build('path.storage')
#2 /data/www/eureka/APJ-api/vendor/laravel/framework/src/Illuminate/Container/Container.php(601): Illuminate\Container\Container->resolve('path.storage', Array)
#3 /data/www/eureka/APJ-api/vendor/laravel/lumen-framework/src/Application.php(221): Illuminate\Container\Container->make('path.storage', Array)
#4 /data/www/eureka/APJ-api/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(119): Laravel\Lumen\Application->make('path.storage', Array)
#5 /data/www/eureka/APJ-api/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(874): a in /data/www/eureka/APJ-api/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 767

In Container.php line 767:
                                                                                                                                                                    
  Uncaught ReflectionException: Class path.storage does not exist in /data/www/eureka/APJ-api/vendor/laravel/framework/src/Illuminate/Container/Container.php:767   
  Stack trace:                                                                                                                                                      
  #0 /data/www/eureka/APJ-api/vendor/laravel/framework/src/Illuminate/Container/Container.php(767): ReflectionClass->__construct('path.storage')                    
  #1 /data/www/eureka/APJ-api/vendor/laravel/framework/src/Illuminate/Container/Container.php(646): Illuminate\Container\Container->build('path.storage')           
  #2 /data/www/eureka/APJ-api/vendor/laravel/framework/src/Illuminate/Container/Container.php(601): Illuminate\Container\Container->resolve('path.storage', Array)  
  #3 /data/www/eureka/APJ-api/vendor/laravel/lumen-framework/src/Application.php(221): Illuminate\Container\Container->make('path.storage', Array)                  
  #4 /data/www/eureka/APJ-api/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(119): Laravel\Lumen\Application->make('path.storage', Array)  
```

**Comment by digitaldreams** [comment]
Not yet. I will test it on lumen an make it compatible in future
